### ISSUE TITLE
Feature: add voice option in tts options

### ISSUE THREAD

**Issue by VinayV9** [nativescript-community/texttospeech#17]
right now am able to get default voice in my phone using native script tts plugin.  is that possible to add voice option so that we can select from available voice options in the phone.

**Comment by VishnuLearning** [comment]
I think we can, because if you look at [Android Text to Speech](https://developer.android.com/reference/android/speech/tts/TextToSpeech), there are methods getVoices() and setVoice().

Similarly in IOS there is option to set voice of utterance. [See here](https://developer.apple.com/documentation/avfoundation/avspeechutterance/1619710-voice).

The Nativescript TTS module need to be updated with these features.

**Comment by mikefromru** [comment]
How can I use a male's voice?

**Comment by chris-praxis** [comment]
Any work on this?  Using default voice is very limiting.

**Comment by farfromrefug** [comment]
We cant easily do that. it all depends on the user settings to download one voice or another.
Android reference: https://stackoverflow.com/questions/18280451/android-texttospeech-set-gender
The only thing you can do is select the locale.
